### ISSUE TITLE
Doesn't install with Node 5.5.0

### ISSUE THREAD

**Issue by theDustRoom** [seriousManual/node-piglow#13]
...and most likely not with 4.2.6 either but will test and update asap.

**Comment by seriousManual** [comment]
hi, this is a known issue. 

unfortunately it has to do with the dependency node-i2c that's not compatible with 4.x and 5.x, this will most likely not change in the immediate future: https://github.com/kelly/node-i2c/issues/69

I'm looking into alternatives to https://github.com/kelly/node-i2c, any help and hints are very much appreciated!

I'll keep this open until a decent solution has been found.

**Comment by fivdi** [comment]
Well, if you're looking into alternatives https://github.com/fivdi/i2c-bus may suit your need.

**Comment by seriousManual** [comment]
thank you, looks good!

**Comment by jamms** [comment]
fivdi, i have 5 or so sensors that did use node-i2c. The drivers for these sensors look for i2c when I install them using npm. I would like to use your i2c-bus instead of node-i2c as your library seems much more up to date. Is it possible to install my sensors so they can be using i2c-bus instead - and how easy is it to do this (as you can tell I'm quite a noob)!

cheers

**Comment by fivdi** [comment]
@jamms you probably should have created a new issue at the i2c-bus repository to ask that question rather than asking it here. This issue is about node-piglows support of Node.js v5.5.0 :)

The answer to the question is that the authors of the sensor drivers that you are using would need to update their modules to use i2c-bus rather than node-i2c. It's not possible to use i2c-bus instead of node-i2c automatically. The corresponding modules need to be updated to use i2c-bus instead. If you are the author of the modules, you could update them to use i2c-bus. If not, you could fork them, update them to use i2c-bus, make pull requests, and perhaps the authors would merge the pull requests.

**Comment by jamms** [comment]
Ach! Yes, you're right, apologies for messing up this thread :(

However, you answered my question and its what I suspected, but wasn't too sure about so I take my hat off to you for that. At least I can look around for alternative sensor drivers that work with i2c-bus (I do not have a lot of time in my life to learn how to re-write this kind of stuff) - rather than barking up the wrong tree with node-i2c - cheers!

**Comment by YeomansIII** [comment]
I am getting these ic2 build errors on every version of node that I have tried.  Is there a specific version I should be using?

https://gist.github.com/YeomansIII/facf5a5978e5506ff99e

**Comment by seriousManual** [comment]
hi,
the i2c dep works up until node v0.11, it seems you have been trying to install with node 0.12.4?

**Comment by thisdavej** [comment]
The issue with https://github.com/kelly/node-i2c/issues/69 was resolved a couple months ago.  I updated the node-piglow package.json dependencies on my local system and changed i2c to "^0.2.3".  I was then able to do an npm install with node 6.3.1 (in my case) on my rasPi and it worked!  @seriousManual, can update the i2c version in the package.json? I would also like to use your piglow-cli since it looks awesome too.

**Comment by seriousManual** [comment]
thank you very much for the heads up!

i just released v3 with the upgraded dependencies.
this is a major release because of the dropped 0.10 and 0.12 support.

i will update the dependencies of the other piglow-* modules in the very near future (today-ish)
